### PR TITLE
Update branch after Create completion PR

### PR DESCRIPTION
**Pull request by adrbessy**
Update branch after Create completion PR

### CODE REVIEW

**Comment by SPalominos** [comment]
You have useless file in you PR (files in the `.idea` folder for example), you should add a `.gitignore` file to filter those files. 
You have an exemple [here](https://github.com/orbisgis/h2gis/blob/master/.gitignore), and you have the doc about it [here](https://git-scm.com/docs/gitignore).

**Comment by ebocher** [comment]
@SPalominos good catch
@adrbessy  Be carefull, take care to not commit unnecessary files.

**Comment by nicolas-f** [comment]
Hello. You should not add more commit. You have to redo the first commit without the unwanted files.

**Review by ebocher — COMMENTED** [review]
It will be better to add another name to the jar dependencies .

**Comment by ebocher** [comment]
> It will be better to add another name to the jar dependencies .

Do not take into account this comment.

**Review by ebocher — APPROVED** [review]

**Pull request merged**
